version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"] 
  invidious:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - misaka
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: invidious.nori.moe
      LETSENCRYPT_HOST: invidious.nori.moe

volumes:
  postgresdata:

networks:
  misaka:
    external: true
